Replace user edit form with Crispy Forms
buza-project/buza-website pull request #55
Opened 2018-10-13 16:09 UTC by sw00

Small PR to get acquainted with Django and Crispy Forms.

2018-10-14 18:13 UTC, pjdelport commented
Cool, thanks for starting this! :)

For the Travis failure, we use [isort](https://github.com/timothycrosley/isort) to automatically sort all our imports: this helps keep things consistent, and makes it so that we have one less thing to manually worry about.

To run isort, you can just run `isort --apply` in your working copy before making a commit: that will sort everything in isort's standardised order and format. (I did this in commit 6112065.) If you can, you can set up your editor to do this automatically, or with a shortcut.

2018-10-14 19:07 UTC, pjdelport commented
The next thing we should probably do is to migrate the `buza.views.edit` view to a generic Django `UpdateView`, so that we can use our `CrispyFormMixin` to handle the common parts of adding the `FormHelper`, and customise it there.

The `QuestionCreate` / `QuestionUpdate` views (with their common code in `QuestionModelFormMixin`) are an existing example of how to approach that.

2018-10-16 18:53 UTC, sewagodimo submitted a review, later dismissed
:cake: :beer:

2018-10-21 20:48 UTC, sw00 commented
Re https://github.com/buza-project/buza-website/pull/55/commits/2e6c0959e4369a841997591d083a4aae5f76015b: just did a haphazard change in the interest of exploring. Tests are failing but need to determine whether they still make sense with regards to new implementation or just [change detectors](https://testing.googleblog.com/2015/01/testing-on-toilet-change-detector-tests.html).

Also, sorry for the slow progress. Haven't had much time this week and just getting re-acquainted with stack after years of being away from Django/Python webdev.

2018-10-21 20:49 UTC, pjdelport commented on src/buza/views.py
> +class EditUser(LoginRequiredMixin, generic.UpdateView):
```suggestion
class EditUser(CrispyFormMixin, LoginRequiredMixin, generic.UpdateView):
```

2018-10-21 20:57 UTC, pjdelport commented on src/buza/urls.py
> +    path(r'edit/<int:pk>/', views.EditUser.as_view(), name='edit'),
```suggestion
    path(r'edit/<int:pk>/', views.UserUpdate.as_view(), name='user-update'),
```

2018-10-21 20:57 UTC, pjdelport commented on src/buza/views.py
> +        helper.form_action = reverse('edit')
```suggestion
        helper.form_action = reverse('user-update')
```

2018-10-21 21:05 UTC, pjdelport commented
@sw00: Cool! The tests are failing because the view's URL now actually takes a parameter: they should be updated for that.

We'll also need to add some authorisation, so that users can only edit themselves (as an initial policy), for which we can probably pull in https://github.com/pjdelport/django-auth-utils

2018-10-22 21:21 UTC, pjdelport commented
@sw00: Okay, I added some changes, removed the old edit view and form that this replaces, and update the tests. How does this look to you? (And thanks for getting this started! :D)

@sewagodimo: The actual design could probably use more tweaking as we go on, but this PR should be good to merge as it stands. Are you happy with it?

2018-11-01 20:40 UTC, PiDelport requested changes

2018-11-01 20:40 UTC, pjdelport commented on src/buza/views.py
> +            raise PermissionDenied('You can only update your own profile.')
We should ideally test this check before merging…

2019-01-07 20:13 UTC, PiDelport approved these changes

2019-01-07 20:17 UTC, pjdelport commented
Let's get this merged! Thanks. :coffee:

2019-01-07 20:18 UTC, merged

2019-01-07 20:18 UTC, sewagodimo reviewed
approved