Updating the question form UI to be much simpler
buza-project/buza-website pull request #56
Opened 2018-10-16 18:56 UTC by sewagodimo

2018-10-17 21:20 UTC, pjdelport commented
This sounds like a good simplification, yes!

2018-10-17 21:22 UTC, PiDelport commented on src/buza/templates/buza/question_form.html
> +</form>
So just to make sure I understand, the layout above is the suggested alternative to the previous / default layout below?

2018-10-17 21:28 UTC, PiDelport requested changes
We'll also probably want to:

- [ ] Update the model to remove the heading too
- [ ] Use crispy-forms for the new layout

We can tackle that tomorrow at Codebridge? :)

2018-10-18 16:12 UTC, sewagodimo commented on src/buza/templates/buza/question_form.html
> +</form>
yes

2018-10-20 10:56 UTC, sewagodimo commented
@pjdelport I am closing this because a question will just be a textfield

2018-10-20 10:57 UTC, closed without merging

2018-10-20 23:29 UTC, PiDelport commented
Cool! Yeah, we have a much better aim now, I think. :)